blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostIndexView.as_view(), name='index'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='detail'),
    path('search/', views.search, name='search'),
]

comments/urls.py
from django.urls import path

from . import views

app_name = 'comments'
urlpatterns = [
    path('comment/<int:post_pk>', views.comment, name='comment'),
]

hhxdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from posts.views import PostViewSet, PostIndexView, page_not_found
from comments.views import CommentViewSet

router = routers.DefaultRouter()
router.register(r"comments", CommentViewSet, basename="comment")
router.register(r"post", PostViewSet, basename="post")
urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("post/", include("posts.urls")),
    path("comment/", include("comments.urls")),
    path("", PostIndexView.as_view()),
    path("book/", include("books.urls")),
    path("api/", include(router.urls)),
    path("api/auth/", include("rest_framework.urls", namespace="rest_framework")),
]

handler404 = page_not_found

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostIndexView.as_view(), name='index'),
    path('<int:pk>', views.PostDetailView.as_view(), name='detail'),
    path('search/', views.search, name='search'),
]

posts/models.py
import markdown
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.html import strip_tags


# Create your models here.
class Category(models.Model):
    name = models.CharField('分类', max_length=100)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField('标签', max_length=100)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField('标题', max_length=100)
    body = models.TextField('正文')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    modified_time = models.DateTimeField('修改时间')
    excerpt = models.CharField('摘要', max_length=200, blank=True)
    category = models.ForeignKey(
        Category, verbose_name='分类', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)
    author = models.ForeignKey(
        User, verbose_name='作者', on_delete=models.CASCADE)
    views = models.PositiveIntegerField('访问量', default=0, editable=False)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        self.excerpt = strip_tags(md.convert(self.body))[:100]
        super().save(*args, **kwargs)

    def increase_view(self):
        self.views += 1
        self.save(update_fields=['views'])

posts/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render
from django.views import generic
from rest_framework.decorators import action
from rest_framework.pagination import PageNumberPagination
# from rest_framework.permissions import AllowAny
from rest_framework import viewsets, mixins

from comments.serializers import CommentSerializer
from .models import Post
from .serializers import PostListSerializer, PostRetrieveSerializer
from comments.forms import CommentForm
from comments.models import Comment


class PostIndexView(generic.ListView):
    model = Post
    template_name = 'posts/index.html'
    paginate_by = 10

    # context_object_name = 'post_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Blog'
        return context


class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'posts/detail.html'

    # context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = context.get('object')
        context['comment_form'] = CommentForm()
        context['comment_list'] = Comment.objects.all()
        return context


def search(request):
    q = request.POST.get('q')
    if not q:
        error_msg = "请输入关键词"
        messages.add_message(request, messages.ERROR,
                             error_msg, extra_tags='danger')
    post_list = Post.objects.filter(
        Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'posts/index.html', {'post_list': post_list, 'title': 'Blog'})


def page_not_found(request, exception):
    return render(request, 'errors/404.html')


class PostViewSet(mixins.ListModelMixin, viewsets.GenericViewSet, mixins.RetrieveModelMixin,mixins.CreateModelMixin):
    serializer_class = PostListSerializer
    queryset = Post.objects.all()
    pagination_class = PageNumberPagination

    def get_serializer_class(self):
        if self.action == 'list':
            return PostListSerializer
        elif self.action == 'retrieve':
            return PostRetrieveSerializer
        else:
            return super().get_serializer_class()

    # permission_classes = [AllowAny]
    @action(
        methods=["GET"],
        detail=True,
        url_path="comments",
        url_name="comment",
        pagination_class=PageNumberPagination,
        serializer_class=CommentSerializer,
    )
    def list_comments(self, request, *args, **kwargs):
        post = self.get_object()
        queryset = post.comment_set.all()
        page = self.paginate_queryset(queryset)
        serializer = self.get_serializer(page, many=True)
        return self.get_paginated_response(serializer.data)

templates/posts/detail.html
{% extends 'base.html' %}
{% block main %}
    <div class="container">
        <h1 class="detail-title">{{ post.title }}</h1>
        <hr>
        {{ post.body|safe }}
    </div>
    <div class="container">
        <h3>发表评论</h3>
        <hr>
        <div class="col-md-10">
            <form action="{% url 'comments:comment' post.pk %}" method="post" role="form" class="form-horizontal">
                {% csrf_token %}
                {{ comment_form }}
                <button type="submit" class="form-control">发表</button>
            </form>
        </div>
    </div>
    <div class="container">
        <h3>评论列表,共{{ comment_count }}条评论</h3>
        <hr>
        <ul>
            {% for comment in comment_list %}
                <li>{{ comment.name }}{{ comment.created_time }}</li>
                <p>{{ comment.text }}</p>
            {% endfor %}
        </ul>
    </div>
{% endblock main %}

templates/posts/index.html
{% extends 'base.html' %} %}
{% block main %}
    <div class="container">
        {% for post in post_list %}
            <article>
                <header>
                    <h3>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </h3>
                </header>
                <span>
                    {{ post.modified_time }}
                    By {{ post.author }}
                    Under <a href="javascript:void(0);">{{ post.category }}</a>
                    Views {{ post.views }}
                </span>
                <span>{{ post.excerpt }}</span>
            </article>
        {% empty %}
            <div class="container">Nothing!</div>
        {% endfor %}
    </div>
{% endblock main %}