blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostIndexView.as_view(), name='index'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='detail'),
    path('search/', views.search, name='search'),
]

books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.BookIndexView.as_view(), name='index'),
]

hhxdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from posts.views import PostViewSet, PostIndexView, page_not_found
from comments.views import CommentViewSet

router = routers.DefaultRouter()
router.register(r"comments", CommentViewSet, basename="comment")
router.register(r"post", PostViewSet, basename="post")
urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("post/", include("posts.urls")),
    path("comment/", include("comments.urls")),
    path("", PostIndexView.as_view()),
    path("book/", include("books.urls")),
    path("api/", include(router.urls)),
    path("api/auth/", include("rest_framework.urls", namespace="rest_framework")),
]

handler404 = page_not_found

books/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Author(models.Model):
    name = models.CharField('作者', max_length=100)

    class Meta:
        verbose_name = '作者'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class BookInfo(models.Model):
    name = models.CharField('书籍', max_length=200)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    description = models.TextField('简介')
    create_time = models.DateTimeField('创建时间', auto_now=True)
    index = models.IntegerField('顺序', default=1)

    class Meta:
        verbose_name = '书籍'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("books:chapter", kwargs={"book_pk": self.pk})


class Chapter(models.Model):
    title = models.CharField('标题', max_length=200)
    index = models.IntegerField('顺序')
    body = models.TextField('正文')
    book = models.ForeignKey(
        BookInfo, verbose_name='书籍', on_delete=models.CASCADE)
    parent = models.IntegerField('上级章节', default=0)

    class Meta:
        verbose_name = '章节'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:detail", kwargs={"index": self.index, "book_pk": self.book.pk})

books/views.py
from django.views import generic
from .models import BookInfo


class BookIndexView(generic.ListView):
    model = BookInfo
    template_name = 'books/index.html'

templates/books/chapter.html
{% extends 'base.html' %} %}
{% block main %}
    <div class="container">
        <ul>
            {% for chapter in chapter_list %}
                <li>
                    <a href="{{ chapter.get_absolute_url }}">{{ chapter.title }}</a>
                </li>
            {% empty %}
                <div class="container">Nothing!</div>
            {% endfor %}
        </ul>
    </div>
{% endblock main %}

templates/books/detail.html
{% extends 'base.html' %} %}
{% block main %}
    <div class="container">
        <h1>{{ chapter.title }}</h1>
        <hr>
        {{ chapter.body|safe }}
    </div>
{% endblock main %}

templates/books/index.html
{% extends 'base.html' %} %}
{% block main %}
    <div class="container">
        {% for book in bookinfo_list %}
            <article>
                <header>
                    <h3>
                        <a href="{{ book.get_absolute_url }}">{{ book.name }}</a>
                    </h3>
                </header>
                <span>By {{ book.author }}</span>
                <span>{{ book.description }}</span>
            </article>
        {% empty %}
            <div class="container">Nothing!</div>
        {% endfor %}
    </div>
{% endblock main %}