blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostIndexView.as_view(), name='index'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='detail'),
    path('search/', views.search, name='search'),
]

hhxdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from posts.views import PostViewSet, PostIndexView, page_not_found
from comments.views import CommentViewSet

router = routers.DefaultRouter()
router.register(r"comments", CommentViewSet, basename="comment")
router.register(r"post", PostViewSet, basename="post")
urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("post/", include("posts.urls")),
    path("comment/", include("comments.urls")),
    path("", PostIndexView.as_view()),
    path("book/", include("books.urls")),
    path("api/", include(router.urls)),
    path("api/auth/", include("rest_framework.urls", namespace="rest_framework")),
]

handler404 = page_not_found

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostIndexView.as_view(), name='index'),
    path('<int:pk>', views.PostDetailView.as_view(), name='detail'),
    path('search/', views.search, name='search'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/x-icon" />
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <style>
        span {
            display: block;
        }

        p {
            text-indent: 2em;
        }
    </style>
    <title>{{ title }}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" role="navigation">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
            aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="/">MySite</a>
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="/post/">Blog</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/book/">Book</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/admin/" target="_blank">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/api/" target="_blank">API</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/vue/" target="_blank">Vue</a>
                </li>
            </ul>
            <form role="search" method="post" action="{% url 'posts:search' %}" class="form-inline my-2 my-lg-0">
                {% csrf_token %}
                <input type="search" name="q" placeholder="输入关键字" required class="form-control mr-sm-2">
                <button type="submit" class="btn">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z" />
                        <path fill-rule="evenodd"
                            d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" />
                    </svg>
                </button>
            </form>
        </div>
    </nav>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <main>
        {% block main %}
        {% endblock main %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>